### PR TITLE
update import to support latest grails 3.2.8

### PR DESCRIPTION
**Pull request by martinduris**

### CODE REVIEW

**Comment by senty** [comment]
related to issue : https://github.com/splix/grails-spring-security-facebook/issues/94

**Comment by splix** [comment]
Is it compatible with older versions of grails 3.x.x?

**Comment by senty** [comment]
@splix nope ... after 3.2.x "old package" is not present
(i think from 3.1.14 is marked as deprecated)

**Comment by splix** [comment]
Ok, I'll make a release later today. Thank you

**Comment by senty** [comment]
thanks

**Comment by senty** [comment]
@splix have you manage to do release ? thanks

**Comment by splix** [comment]
@senty oh, sorry, was so busy with other stuff. I put it into my list now, will do asap

**Pull request merged**
